apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::371621927995:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-16S9A471MCUFQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::371621927995:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-04T14:19:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1514"
  uid: 9a5f5d24-84b0-4869-b72f-af8c874accc7
